services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always  # ðŸ”¥ Auto-restart if crash or reboot
    networks:
      - fortinet_net
    secrets:
      - fortigate_api_token
    volumes:
      - ./app/certs:/app/certs
    environment:
      - FORTIGATE_API_TOKEN_FILE=/run/secrets/fortigate_api_token
      - FORTIGATE_CERT_PATH=/app/certs/fortigate.pem
      - FORTIGATE_HOST=https://192.168.0.254
      - LOG_LEVEL=DEBUG

  wan_monitor:
    build:
      context: .
      dockerfile: Dockerfile.wan_monitor
    restart: always
    networks:
      - fortinet_net
    environment:
      - FORTIGATE_HOST=https://192.168.0.254
      - API_TOKEN=hmNqQ0st7xrjnyQHt8dzpnkqm5hw5N

secrets:
  fortigate_api_token:
    file: ./secrets/fortigate_api_token.txt

networks:
  fortinet_net:
    driver: bridge